lib/tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

from django.conf.urls.defaults import *

urlpatterns = patterns('tinymce.views',
    url(r'^js/textareas/(?P<name>.+)/$', 'textareas_js', name='tinymce-js'),
    url(r'^js/textareas/(?P<name>.+)/(?P<lang>.*)$', 'textareas_js', name='tinymce-js-lang'),
    url(r'^spellchecker/$', 'spell_check'),
    url(r'^flatpages_link_list/$', 'flatpages_link_list'),
    url(r'^compressor/$', 'compressor', name='tinymce-compressor'),
    url(r'^filebrowser/$', 'filebrowser', name='tinymce-filebrowser'),
    url(r'^preview/(?P<name>.+)/$', 'preview', name='tinymce-preview'),
)

urls.py
import os.path

from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
import django.contrib.auth.views

from django.contrib import admin
admin.autodiscover()

from contact_form.forms import AkismetContactForm
from feeds import feeds
from breakout.models import VenueSitemap, BreakoutSessionSitemap

sitemaps = {
    'venues': VenueSitemap,
    'breakout_sessions': BreakoutSessionSitemap,
}

urlpatterns = patterns('',
    url(r'^', include('breakout.urls')),
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^oauth/twitter/', include('twitter_app.urls')),
    url(r'^accounts/', include('account.urls')),

    url(r'^contact/$', 'contact_form.views.contact_form', { 'form_class': AkismetContactForm }, name='contact_form'),
    url(r'^contact/sent/$', direct_to_template, { 'template': 'contact_form/contact_form_sent.html' }, name='contact_form_sent'),
    url(r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed', {'feed_dict': feeds}),
    url(r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', { 'sitemaps': sitemaps }),
    url(r'^robots.txt', 'django_robots.urls.rules_list', name='robots_rule_list'),
    # url(r"^announcements/", include('django_announcements.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(.*)$', 'django.views.static.serve', kwargs={'document_root': os.path.join(settings.PROJECT_PATH, 'media')}),
    	url(r'^storage/(?P<path>.*)$','django.views.static.serve',kwargs={'document_root': os.path.join(settings.PROJECT_PATH, 'storage')}),
    )

breakout/forms.py
import datetime
import pytz

from django.conf import settings
from django import forms
from django.forms.formsets import *
from django.forms.util import ErrorList
from django.utils.translation import ugettext as _
from django.utils.html import escape, conditional_escape
from django.utils.safestring import mark_safe
from django.utils.encoding import StrAndUnicode, force_unicode
from django.contrib.sites.models import Site
from django.contrib.auth.models import *
from django.contrib.contenttypes.models import ContentType
from django.template.loader import render_to_string
from django.db.models import Q

from models import *

class BreakoutSessionForm(forms.ModelForm):    
    start_date = forms.DateTimeField(label='Starting Date and Time', input_formats=('%m/%d/%Y %I:%M %p', ))
    end_date = forms.DateTimeField(label='Ending Date and Time', input_formats=('%m/%d/%Y %I:%M %p', ))
    session_format = forms.ModelChoiceField(queryset=BreakoutSessionFormat.objects.all().order_by('name'))
    
    def clean(self):
        super(BreakoutSessionForm, self).clean()
        cleaned_data = self.cleaned_data
        if not ('start_date' in cleaned_data) or not ('end_date' in cleaned_data) or not ('timezone' in cleaned_data):
            # there are missing fields, so just return since the required fields already have errors
            return self.cleaned_data
        
        # get the declared timezone
        timezone = pytz.timezone(cleaned_data['timezone'])
        
        # make sure that the start_date is before the end_date
        
        # localize the start_date using the timezone
        localized_start_date = timezone.localize(cleaned_data['start_date'])
        # convert the start_date to UTC
        utc_start_date = localized_start_date.astimezone(pytz.utc)
        # recreate the start_date stripping the timezone (since we can't have a timezone)
        cleaned_utc_start_date = datetime.datetime(utc_start_date.year, utc_start_date.month, utc_start_date.day, utc_start_date.hour, utc_start_date.minute)
        cleaned_data['start_date'] = cleaned_utc_start_date
        print cleaned_utc_start_date
        # localize the end_date using the timezone
        localized_end_date = timezone.localize(cleaned_data['end_date'])
        # convert the end_date to UTC
        utc_end_date = localized_end_date.astimezone(pytz.utc)
        # recreate the end_date stripping the timezone (since we can't have a timezone)
        cleaned_utc_end_date = datetime.datetime(utc_end_date.year, utc_end_date.month, utc_end_date.day, utc_end_date.hour, utc_end_date.minute)
        cleaned_data['end_date'] = cleaned_utc_end_date
        
        return cleaned_data
    
    class Meta:
        model = BreakoutSession
        exclude = ('moderator', 'registered_users', )
        # fields = ('name', 'description', 'start_date', 'end_date', 'venue', 'session_format', 'available_spots', )

breakout/views/breakout_session.py
import datetime
import vobject

from django.contrib.auth.decorators import login_required, permission_required
from django.conf import settings
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.utils.encoding import smart_unicode, force_unicode
from django.views.decorators.cache import never_cache
from django.contrib.sites.models import Site

from ..models import Venue, BreakoutSession, BreakoutSessionFormat, SessionAttendance
from ..forms import BreakoutSessionForm

def index(request):
    today = datetime.datetime.utcnow()
    breakout_sessions = BreakoutSession.objects.filter(start_date__gte=datetime.datetime(today.year, today.month, today.day, 0, 0, 0)).order_by('start_date')
    return render_to_response('breakout_session/index.html', { 'breakout_sessions': breakout_sessions, }, context_instance=RequestContext(request))    

def list(request, session_format_slug=None, venue_slug=None, include_future=True, include_past=True):
    today = datetime.datetime.utcnow()
    past_breakout_sessions = BreakoutSession.objects.filter(start_date__lt=datetime.datetime(today.year, today.month, today.day, 0, 0, 0)).order_by('-start_date')[0:5]
    session_formats = BreakoutSessionFormat.objects.all().order_by('name')
    breakout_sessions = BreakoutSession.objects.all().order_by('end_date')
    if hasattr(request, 'session_format'):
        breakout_sessions = breakout_sessions.filter(session_format=request.session_format)
    if hasattr(request, 'venue'):
        breakout_sessions = breakout_sessions.filter(venue=request.venue)
    if not include_past:
        breakout_sessions = breakout_sessions.filter(start_date__gte=datetime.datetime(today.year, today.month, today.day, 0, 0, 0))
    elif not include_future:
        breakout_sessions = breakout_sessions.filter(end_date__lt=datetime.datetime(today.year, today.month, today.day, 0, 0, 0))
    return render_to_response('breakout_session/list.html', 
                                { 'breakout_sessions': breakout_sessions, 
                                  'include_future': include_future,
                                  'include_past': include_past, }, 
                                context_instance=RequestContext(request))    

def view(request, venue_slug, breakout_session_id):
    try:
        breakout_session = BreakoutSession.objects.filter(venue=request.venue).get(pk=breakout_session_id)
        return render_to_response('breakout_session/view.html', { 'breakout_session': breakout_session }, context_instance=RequestContext(request))
    except BreakoutSession.DoesNotExist:
        return HttpResponseRedirect(reverse('index'))        
    except Venue.DoesNotExist:
        return HttpResponseRedirect(reverse('index'))

@never_cache
@login_required
def create(request):
    breakout_session = BreakoutSession(moderator=request.user)
    
    if request.method == 'POST':
        form = BreakoutSessionForm(request.POST, instance=breakout_session)
        if form.is_valid():
            breakout_session = form.save()            
            request.user.message_set.create(message="Session <strong>%s</strong> created" % breakout_session.name)
            if breakout_session.register(request.user):
                request.user.message_set.create(message="You have been registered for this Breakout Session")
            return HttpResponseRedirect(reverse('breakout_session_view', kwargs={ "breakout_session_id": breakout_session.id, "venue_slug": breakout_session.venue.slug }))
    else:
        form = BreakoutSessionForm(instance=breakout_session)
    return render_to_response('breakout_session/create.html', { 'form': form, }, context_instance=RequestContext(request))

@never_cache
@login_required
def register(request, venue_slug, breakout_session_id):
    """
    Registers a user for a session
    
    Session must be taking place, or scheduled for the future
    """
    try:
        breakout_session = BreakoutSession.objects.filter(venue=request.venue).get(pk=breakout_session_id)
        if breakout_session.register(request.user):
            request.user.message_set.create(message="You have been registered for this Breakout Session")
        return HttpResponseRedirect(reverse('breakout_session_view', kwargs={ "breakout_session_id": breakout_session.id, "venue_slug": breakout_session.venue.slug }))
    except BreakoutSession.DoesNotExist:
        request.user.message_set.create(message="Breakout Session does not exist")
        return HttpResponseRedirect(reverse('index'))

@never_cache
@login_required
def unregister(request, venue_slug, breakout_session_id):
    """
    Registers a user for a session
    """
    try:
        breakout_session = BreakoutSession.objects.filter(venue=request.venue).get(pk=breakout_session_id)
        if breakout_session.unregister(request.user):
            request.user.message_set.create(message="You have been un-registered for this Breakout Session")
        return HttpResponseRedirect(reverse('breakout_session_view', kwargs={ "breakout_session_id": breakout_session.id, "venue_slug": breakout_session.venue.slug }))
    except BreakoutSession.DoesNotExist:
        request.user.message_set.create(message="Breakout Session does not exist")
        return HttpResponseRedirect(reverse('index'))
    except SessionAttendance.DoesNotExist:
        request.user.message_set.create(message="You aren't registered for this Breakout Session")
        return HttpResponseRedirect(reverse('breakout_session_view', kwargs={ "breakout_session_id": breakout_session.id, "venue_slug": breakout_session.venue.slug }))

@never_cache
@login_required
def checkin(request, venue_slug, breakout_session_id):
    """
    Checks a user into a session
    """
    try:
        breakout_session = BreakoutSession.objects.filter(venue=request.venue).get(pk=breakout_session_id)
        if breakout_session.checkin(request.user):
            request.user.message_set.create(message="You have been checked into this Breakout Session")
        return HttpResponseRedirect(reverse('breakout_session_view', kwargs={ "breakout_session_id": breakout_session.id, "venue_slug": breakout_session.venue.slug }))
    except BreakoutSession.DoesNotExist:
        request.user.message_set.create(message="Breakout Session does not exist")
        return HttpResponseRedirect(reverse('index'))        

@never_cache
@login_required
def checkout(request, venue_slug, breakout_session_id):
    """
    Checks a user out of a session
    """
    try:
        breakout_session = BreakoutSession.objects.filter(venue=request.venue).get(pk=breakout_session_id)
        if breakout_session.checkout(request.user):
            request.user.message_set.create(message="You have been checked out of this Breakout Session")
        return HttpResponseRedirect(reverse('breakout_session_view', kwargs={ "breakout_session_id": breakout_session.id, "venue_slug": breakout_session.venue.slug }))
    except BreakoutSession.DoesNotExist:
        request.user.message_set.create(message="Breakout Session does not exist")
        return HttpResponseRedirect(reverse('index'))        

def ical(request):
    """
    Outputs an iCalendar response with all of the upcoming BreakoutSessions
    
    see http://blog.thescoop.org/archives/2007/07/31/django-ical-and-vobject/
    """
    calendar = vobject.iCalendar()
    calendar.add('method').value = 'PUBLISH'  # IE/Outlook needs this
    breakout_sessions = BreakoutSession.objects.all()
    for breakout_session in breakout_sessions:
        vevent = calendar.add('vevent')
        vevent.add('summary').value = breakout_session.name
        vevent.add('description').value = "%s\n\nSession Format: %s\nHosted By: %s" % (breakout_session.description, breakout_session.session_format.name, breakout_session.moderator.short_name, )
        vevent.add('url').value = "http://%s%s" % (Site.objects.get_current().domain, breakout_session.get_absolute_url(), )
        vevent.add('location').value = "%s - %s, %s, %s %s" % (breakout_session.venue.name, breakout_session.venue.street_address_1, breakout_session.venue.city, breakout_session.venue.state, breakout_session.venue.zip_code, )
        vevent.add('dtstart').value = breakout_session.start_date_localized
        vevent.add('dtend').value = breakout_session.end_date_localized
    icalendar_stream = calendar.serialize()
    response = HttpResponse(icalendar_stream, mimetype='text/calendar')
    response['Filename'] = 'breakout_sessions.ics'  # IE needs this
    response['Content-Disposition'] = 'attachment; filename=breakout_sessions.ics'
    return response

templates/breakout_session/create.html
{% extends "base.html" %}
{% load pagination_tags %}
{% load common_tags %}

{% block title %}{% block pagetitle %}Register Breakout Session{% endblock %}{% endblock %}

{% block content %}

{% if venue %}
    {% include "venue/ul.venue_menu.html" %}
{% endif %}

<form action="#" method="POST">

    <span class="error">
        {% for error in form.non_field_errors %}
            {{ error }} {% if not forloop.first %}<br/>{% endif %}
        {% endfor %}
    </span>

    <div class="form">
        {% with form.name as field %}{% include 'form.field.html' %}{% endwith %}
        <div class="clear"></div>
        {% with form.session_tag as field %}{% include 'form.field.html' %}{% endwith %}
        <div class="clear"></div>
        {% with form.session_format as field %}{% include 'form.field.html' %}{% endwith %}
        <div class="clear"></div>

        {% with form.start_date as field %}{% include 'form.field.html' %}{% endwith %}
        {% with form.timezone as field %}{% include 'form.field.html' %}{% endwith %}
        <div class="clear"></div>
        
        {% with form.end_date as field %}{% include 'form.field.html' %}{% endwith %}
        <div class="clear"></div>

        {% with form.description as field %}{% include 'form.field.html' %}{% endwith %}
        <div class="clear"></div>
        
        {% with form.venue as field %}{% include 'form.field.html' %}{% endwith %}
        {% with form.available_spots as field %}{% include 'form.field.html' %}{% endwith %}
        <div class="clear"></div>
    </div>


    <button type="submit">Register Breakout! Session</button>
</form>

<script type="text/javascript">
	$(function() {
	    $.datepicker.setDefaults({
		    showButtonPanel: true, 
		    constrainInput: true, 
		    showTime: true,
		    navigationAsDateFormat: true, 
		    duration: ''
        });
	    
		$("#id_start_date").datepicker({ 
		    defaultDate: '+1d',
		    minDate: '+1d'
		});

		$("#id_end_date").datepicker({ 
		    defaultDate: '+1d',
		    minDate: '+1d'
		});
	});
</script>

{% endblock %}

{# {% block content_secondary %} #}
{#  #}
{# {% include 'breakout_session/sidebar.past_sessions.html' %} #}
{#  #}
{# {% endblock %} #}

templates/breakout_session/index.html
{% extends "base.html" %}
{% load pagination_tags %}
{% load common_tags %}

{% block title %}{% block pagetitle %}Welcome to Breakout!{% endblock %}{% endblock %}

{% block content %}

<p>Breakout! helps people and teams locate stimulating, serene and serendipitous places to work in the city. Whether you're trying to break a creative block, meet people to work on tough problems together, or just looking to escape from your cubicle for a few hours, there's a "breakout session" for that. Follow us on Twitter (<a href="http://www.twitter.com/breakoutnow" target="_blank">@breakoutnow</a>).</p>

<div class="subscribe"><a href="{% url breakout_session_list_ical %}"><img src="{{ MEDIA_URL }}images/onebit_clock.png"> Subscribe in iCal</a></div>

<div class="subscribe"><a href="/feeds/sessions/"><img src="{{ MEDIA_URL }}images/onebit_rss.png"> Subscribe to RSS</a></div>

<h2>All Upcoming Sessions</h2>

{% regroup breakout_sessions by event_date as breakout_session_dates_list %}

{% for breakout_session_dates in breakout_session_dates_list %}
<div class="breakout-session-list-date">{{ breakout_session_dates.grouper|date:"l, F dS" }}</div>
<div class="breakout-session-list">
    {% for breakout_session in breakout_session_dates.list %}
        {% include 'breakout_session/table.list.html' %}
    {% endfor %}
</div>

{% endfor %}

{% endblock %}

templates/breakout_session/list.html
{% extends "base.html" %}
{% load pagination_tags %}
{% load common_tags %}

{% block title %}{% block pagetitle %}
    {% if not include_future %}Past {% endif %}
    {% if not include_past %}Upcoming {% endif %}
    Breakout Sessions
    {% if session_format %} in {{ session_format.name }}{% endif %}
{% endblock %}{% endblock %}

{% block content %}

{% if venue %}
    {% include "venue/ul.venue_menu.html" %}
{% endif %}

{% if session_format %}
{{ session_format.description|safe|urlize|linebreaks }}
{% endif %}

{% regroup breakout_sessions by event_date as breakout_session_dates_list %}

{% for breakout_session_dates in breakout_session_dates_list %}

    <div class="breakout-session-list-date">{{ breakout_session_dates.grouper|date:"l, F jS" }}</div>

    <div class="breakout-session-list">
        {% for breakout_session in breakout_session_dates.list %}
            {% include 'breakout_session/table.list.html' %}
        {% endfor %}
    </div>

{% endfor %}

{% endblock %}

templates/breakout_session/sidebar.categories.html
<div class="sidebar-container">
    
    <h2>Session Formats</h2>
    
    <div class="sidebar-information">
        <p>There are different kinds of breakout session formats for different people and different needs. Browse the different kinds of meetings and see upcoming sessions.</p>
    
        <ul class="category-list">
            {% for category in categories %}
                <li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
            {% endfor %}
        </ul>
    </div>    
</div>

templates/breakout_session/sidebar.host_session.html
<div class="host-session-action">
    <a href="{% url breakout_session_create %}"><img src="{{ MEDIA_URL }}images/bobox.gif" />Host a Breakout Session</a>
</div>

templates/breakout_session/sidebar.participants.html
{% load common_tags %}

{% if breakout_session.registered_users.count %}

<div class="sidebar-container">
    
    <h2>
        {% if breakout_session.is_future %}Registered to Attend{% endif %}
        {% if breakout_session.is_active %}Here Now{% endif %}
        {% if breakout_session.is_past %}Participants{% endif %}
    </h2>
    
    {% if breakout_session.is_active %}
    <div class="breakout-session-participation-bar">
        {% if breakout_session|is_participating:request.user %}
            Thanks for participating! &mdash; <a href="{% url breakout_session_checkout venue_slug=breakout_session.venue.slug, breakout_session_id=breakout_session.id %}">Check Out</a>
        {% endif %}

        {% if not breakout_session|is_participating:request.user %}
            <a href="{% url breakout_session_checkin venue_slug=breakout_session.venue.slug, breakout_session_id=breakout_session.id %}">Are you at this Breakout Session?</a>
        {% endif %}
    </div>
    {% endif %}

    <div class="sidebar-information">
        <div class="participant-list">
            {% if breakout_session.participants %}
                {% for participant in breakout_session.participants %}
                    <div class="participant" style="border-left: 4px solid #4de;">
                        <a href="{{ participant.get_absolute_url }}">
                            {% if participant.get_profile.twitter_user.profile_image_url %}
                                <img class="profile-image" src="{{ participant.get_profile.twitter_user.profile_image_url }}" />
                            {% else %}
                                <img class="profile-image" src="{{ participant.get_profile.profile_image.url }}">
                            {% endif %}
                            {% ifequal participant request.user %}<strong>You!</strong>
                            {% else %}{{ participant.short_name }}{% endifequal %}
                        </a>

                    </div>
                {% endfor %}
            {% else %}
                {% for registrant in breakout_session.registered_users.all %}
                    <div class="participant" style="border-left: 4px solid #4de;">
                        <a href="{{ registrant.get_absolute_url }}">
                            {% if registrant.get_profile.twitter_user.profile_image_url %}
                                <img class="profile-image" src="{{ registrant.get_profile.twitter_user.profile_image_url }}" />
                            {% else %}
                                <img class="profile-image" src="{{ registrant.get_profile.profile_image.url }}">
                            {% endif %}
                            {% ifequal registrant request.user %}<strong>You!</strong>
                            {% else %}{{ registrant.short_name }}{% endifequal %}
                        </a>

                    </div>
                {% endfor %}
            {% endif %}
        </div>
    
    </div>
</div>

{% endif %}

templates/breakout_session/sidebar.past_sessions.html
{% if venue.recent_past_breakout_sessions %}
    <div class="sidebar-container">
        <h2>{{ venue.recent_past_breakout_sessions.count }} Past Breakout Sessions Here</h2>

        <div class="sidebar-information">
            <p>View the "meeting minutes" from past sessions &ndash; the collected social media posted by people who participated.</p>

            {% with venue.recent_past_breakout_sessions as breakout_sessions %}
                {% with breakout_session as ignored_session %}
                    {% include 'breakout_session/ul.list.small.html' %}
                {% endwith %}
            {% endwith %}

            <p><a href="{% url archive_breakout_session_list venue_slug=venue.slug %}">View More &raquo;</a></p>
        </div>
    </div>
{% else %}
    {% if past_breakout_sessions or venue.recent_past_breakout_sessions %}
        <div class="sidebar-container">
            <h2>{{ past_breakout_sessions.count }} Past Breakout Sessions{% if venue %} Here{% endif %}</h2>

            <div class="sidebar-information">
                <p>View the "meeting minutes" from past sessions &ndash; the collected social media posted by people who participated.</p>

                {% with past_breakout_sessions as breakout_sessions %}
                    {% with breakout_session as ignored_session %}
                        {% include 'breakout_session/ul.list.small.html' %}
                    {% endwith %}
                {% endwith %}

                <p><a href="{% url past_breakout_session_list %}">View More &raquo;</a></p>
            </div>
        </div>
    {% endif %}

{% endif %}

templates/breakout_session/sidebar.session_formats.html
<div class="sidebar-container">
    
    <h2>Session Formats</h2>
    
    <div class="sidebar-information">
        <p>There are different kinds of breakout session formats for different people and different needs. Browse the different kinds of meetings and see upcoming sessions.</p>
    
        {% for session_format in session_formats %}
            <a href="{{ session_format.get_absolute_url }}">{{ session_format.name }}</a><br/>
        {% endfor %}
    </div>    
</div>

templates/breakout_session/table.list.html
{% load common_tags %}

<table class="breakout-session-list-container">
    <tr>
        <td class="breakout-session-list-description">
            <p>
                <a href="{{ breakout_session.get_absolute_url }}">{{ breakout_session.name }}</a>
                {% if not venue %} at <a href="{{ breakout_session.venue.get_absolute_url }}">{{ breakout_session.venue.name }}</a>{% endif %}
            </p>
            {{ breakout_session.description|safe|urlize|linebreaks }}
        </td>
        <td class="breakout-session-list-details">
            <p>
                <strong>Session Format</strong><br/>
                <a href="{{ breakout_session.session_format.get_absolute_url }}">{{ breakout_session.session_format }}</a></p>
            <p>
                <strong>Time</strong><br/>
                {{ breakout_session.start_date_localized.time|time:"P" }}&ndash;{{ breakout_session.end_date_localized.time|time:"P" }} ({{ breakout_session.timezone }})
            </p>
            {% if not venue %}
                <p>
                    <strong>Location</strong><br/>
                    {% with breakout_session.venue as venue %}
                        {% include 'venue/div.address.html' %}
                    {% endwith %}
                </p>
            {% endif %}
        </td>
    </tr>
    <tr>
        <td class="breakout-session-list-attending" {% if breakout_session.is_past %}colspan="2"{% endif %}>
            <strong>{{ breakout_session.registered_users.count }} {{ breakout_session.registered_users.count|pluralize:"person,people" }} 
                {% if breakout_session.is_past %}attended{% else %}attending{% endif %}</strong>
            {% if breakout_session.remaining_spots %} / {{ breakout_session.remaining_spots }} spots remaining{% endif %}
            {% if not breakout_session.available_spots %} / Everyone is welcome{% endif %}
        </td>
        {% if breakout_session.is_future or breakout_session.is_active %}
            <td class="breakout-session-list-action">
                    {% if not breakout_session|is_registered:request.user %}
                        <a href="{% url breakout_session_register venue_slug=breakout_session.venue.slug, breakout_session_id=breakout_session.id %}">Sign Up To Attend &raquo;</a>
                    {% else %}
                        <strong>Already Registered!</strong>
                    {% endif %}
            </td>
        {% endif %}
    </tr>
</table>

templates/breakout_session/table.list.small.html
{% load common_tags %}

<table class="breakout-session-list-container">
    <tr>
        <td class="breakout-session-list-description">
            <p>
                <a href="{{ breakout_session.get_absolute_url }}">{{ breakout_session.name }}</a>
                {% if not venue %} at <a href="{{ breakout_session.venue.get_absolute_url }}">{{ breakout_session.venue.name }}</a>{% endif %}
            </p>
            {{ breakout_session.description|safe|urlize|linebreaks }}
        </td>
        <td class="breakout-session-list-details">
            <p>
                <strong>Session Format</strong><br/>
                <a href="{{ breakout_session.session_format.get_absolute_url }}">{{ breakout_session.session_format }}</a></p>
            <p>
                <strong>Time</strong><br/>
                {{ breakout_session.start_date_localized.time|time:"P" }}-{{ breakout_session.end_date_localized.time|time:"P" }} ({{ breakout_session.timezone }})
            </p>
            <p>
                <strong>Location</strong><br/>
                {% with breakout_session.venue as venue %}
                    {% include 'venue/div.address.html' %}
                {% endwith %}
            </p>
        </td>
    </tr>
</table>

templates/breakout_session/ul.list.large.html
<ul class="breakout-session-list">
    {% for breakout_session in breakout_sessions %}
        <li><a href="{{ breakout_session.get_absolute_url }}">{{ breakout_session.name }} on {{ breakout_session.start_date_localized|date:"M j, Y" }}</a></li>
    {% endfor %}
</ul>

templates/breakout_session/ul.list.small.html
<ul class="breakout-session-list-small">
    
    {% for breakout_session in breakout_sessions %}
        {# {% ifnotequal ignored_session breakout_session %} #}
            <li>
                <a href="{{ breakout_session.get_absolute_url }}">{{ breakout_session.name }}</a> from {{ breakout_session.start_date_localized|date:"P" }}-{{ breakout_session.end_date_localized|date:"P" }} on {{ breakout_session.start_date_localized|date:"D, M j" }}
            </li>
        {# {% endifnotequal %} #}
    {% endfor %}

</ul>

templates/breakout_session/ul.session_menu.html
{% load common_tags %}

<div class="tabs">
    <ul id="location-menu">
        <li class="active">
            <a href="{{ venue.current_breakout_session.get_absolute_url }}">
                {% if venue.current_breakout_session %}<span>Current Session</span>{% else %}
                    {% if venue.next_breakout_session %}<span>Upcoming Session</span>{% else %}
                        {% if breakout_session %}<span>Past Session</span>{% endif %}
                    {% endif %}
                {% endif %}
            </a>
        </li>
        <li><a href="{{ venue.get_absolute_url }}"><span>About This Location</span></a></li>
        
        {% if venue.past_breakout_sessions.count %}
            <li><a href="{% url archive_breakout_session_list venue_slug=venue.slug %}"><span>Past Sessions</span></a></li>
        {% endif %}
    </ul>
</div>